pipeline{
    agent{
        node{
            label "ansible-maa-01"
        }
    }
    stages{
        stage('Build'){
            when{
                #changeset "**/*.js"
                changeset GLOB: "*.js"
            }
            steps{
                echo "Step has executed succefully as it has matched the file name *.js"
            }
        }
    }
}
