pipeline{
    agent{
        node{
            label "ansible-maa-01"
        }
    }
    stages{
        stage('First'){
            when{
                    //changeRequest()  //when there is pull request this code executes
                    changeRequest title:"when-pr"  //when there is pull request this code executes

            }
            steps{
                    echo "when there is pull request , this code gets success"
            }
        }
    }
  }
