pipeline{
    agent{
        node{
            label "ansible-maa-01"
        }
    }
    stages{
        stage('First'){
            when{
                    changerequest()  //when there is pull request this code executes
            }
            steps{
                    echo "when there is pull request , this code gets success"
            }
        }
    }
  }
