pipeline{
    agent{
     node{
      label 'ansible-maa-01'
      }
    }
    stages{
        stage('Build'){
            when{
                buildingTag()
            }
            steps{
                echo "Hey I am executing when the this is tagged"
            }
        }
    }
}
