pipeline{
    agent any
    stages{
        stage('Build'){
            when{
                buildingTag()
            }
            steps{
                echo "Hey I am executing when the this is tagged"
            }
        }
    }
}
