pipeline{
    agent any
    options{
        timestamps()
        overrideIndexTriggers(true)
    /*** In case of True - Build scheduled will take place, if false , for a commit the build schedule will not place instead a build should
         be done mannually ***/
    }
    stages{
        stage('Build'){
            steps{
                echo "Hello First Build - v6"
            }
        }
    }
}
