pipeline{
    agent any
    options{
        checkoutToSubdirectory('BK')
    }
    stages{
        stage('Build'){
            steps{
                echo "Build in a 'BK' workspace"
            }
            
        }
    }
    
}
